// ⚠️ Phase 1 자동 이식: 데모 index.html에서 원문 그대로 분리한 코드 (로직 변경 금지 구역)
// 모듈 간 호출·인라인 onclick은 아래 globalThis 등록을 통해 해석된다.
const PIXEL_ART = {
'스위스 태엽 회중시계': { p: { O:'#241a10', G:'#e8b23a', g:'#a3711d', W:'#f5f0e0', K:'#3a3226' }, r: [
'......OOO.......',
'......OGO.......',
'.....OOOOO......',
'....OGGgGGO.....',
'...OGGGGGGGO....',
'..OGWWWWWWWgO...',
'..OGWWWKWWWgO...',
'..OGWWWKWWWgO...',
'..OGWWWKKWWgO...',
'..OGWWWWWWWgO...',
'..OGWWWWWWWgO...',
'...OGGGGGgGO....',
'....OGGgGGO.....',
'.....OOOOO......',
]},
'18K 다이아 세팅 금반지': { p: { O:'#241a10', G:'#e8b23a', g:'#a3711d', W:'#eef4ff', l:'#9cc8f0' }, r: [
'......OOO.......',
'.....OWlWO......',
'.....OlWlO......',
'......OlO.......',
'.....OOOOO......',
'....OGg.gGO.....',
'...OGg...gGO....',
'...OG.....GO....',
'...OGg...gGO....',
'....OGg.gGO.....',
'.....OGGGO......',
'......OOO.......',
]},
'독일제 레인지파인더 카메라': { p: { O:'#241a10', K:'#2e2a26', k:'#4a443c', S:'#c9cdd4', s:'#8a8f9a', W:'#f0f4f8', R:'#c04040' }, r: [
'....OOOO........',
'...OSSSSO.......',
'.OOOOOOOOOOOOO..',
'.OSSSSSSSSSSSO..',
'.OKKKOOOOOKKRO..',
'.OKKOSSSSOKKKO..',
'.OKKOSWssOKKKO..',
'.OKKOSsssOKKKO..',
'.OKKOssssOKKKO..',
'.OKKKOOOOOKKKO..',
'.OKKKKKKKKKKKO..',
'.OOOOOOOOOOOOO..',
]},
'고려청자 상감 매병(추정)': { p: { O:'#241a10', T:'#5aa393', t:'#3d7a6c', W:'#eef4ee' }, r: [
'.....OOOOO......',
'....OTTTTTO.....',
'.....OTTTO......',
'.....OTTTO......',
'....OTTTTTO.....',
'...OTTTTTTTO....',
'..OTTTWWTTTTO...',
'..OTTWTTWTTtO...',
'..OTTTWWTTTtO...',
'..OTTTTTTTttO...',
'...OTTTTTttO....',
'....OTTtttO.....',
'.....OOOOO......',
]},
'인상파풍 풍경 유화': { p: { O:'#241a10', G:'#c89a3a', l:'#9cc0e8', Y:'#f0d060', F:'#4a8a4a', b:'#8a5a2b' }, r: [
'OOOOOOOOOOOOOOOO',
'OGGGGGGGGGGGGGGO',
'OGOOOOOOOOOOOOGO',
'OGOllllllllllOGO',
'OGOlllYYlllllOGO',
'OGOllllllllllOGO',
'OGOFFFFFFFFFFOGO',
'OGOFFbbFFFFFFOGO',
'OGOOOOOOOOOOOOGO',
'OGGGGGGGGGGGGGGO',
'OOOOOOOOOOOOOOOO',
]},
'스위스제 실린더 오르골': { p: { O:'#241a10', B:'#8a5a2b', b:'#5a3617', G:'#e8b23a', K:'#3a3226' }, r: [
'.......K........',
'......KK........',
'..OOOOOOOOOOO...',
'..ObbbbbbbbbO...',
'..ObGGGGGGGbO...',
'..OOOOOOOOOOO...',
'.OBBBBBBBBBBBO..',
'.OBbBBbBBbBBbO..',
'.OBBBBBBBBBBBO..',
'.OOOOOOOOOOOOO..',
]},
'14K 금촉 만년필': { p: { O:'#241a10', G:'#e8b23a', K:'#26222e', k:'#3e3850' }, r: [
'.......O........',
'......OGO.......',
'......OGGO......',
'......OGGO......',
'......OKKO......',
'......OKkO......',
'......OKkO......',
'......OKkO......',
'......OKkO......',
'......OKGO......',
'......OKkO......',
'......OKKO......',
'.......OO.......',
]},
'빅토리아풍 은촛대': { p: { O:'#241a10', S:'#c9cdd4', s:'#8a8f9a', W:'#f5f0e0', Y:'#f0d060', R:'#d06030' }, r: [
'.......Y........',
'......OYRO......',
'.......OO.......',
'......OWWO......',
'......OWWO......',
'......OWWO......',
'.....OSSSSO.....',
'......OSsO......',
'......OSsO......',
'.....OSSsSO.....',
'....OSSSssSO....',
'...OOOOOOOOO....',
]},
'70년대 라이더스 가죽 재킷': { p: { O:'#241a10', K:'#2e2a30', k:'#46414a', s:'#8a8f9a' }, r: [
'..OOOO....OOOO..',
'.OKKKKOOOOKKKKO.',
'OKKKKKOkkOKKKKKO',
'OKKOKKkKKkKKOKKO',
'OKKOKKkKsKKKOKKO',
'OKKOKKkKKkKKOKKO',
'OKKOKKkKsKKKOKKO',
'OKKOKKkKKkKKOKKO',
'.OOOKKKKKKKKOOO.',
'...OOOOOOOOOO...',
]},
'이탈리아 공방 라벨 바이올린': { p: { O:'#241a10', B:'#a2622e', b:'#7a4418', K:'#3a3226' }, r: [
'.......OO.......',
'......ObbO......',
'.......OO.......',
'......ObbO......',
'......ObbO......',
'.....OBBBBO.....',
'....OBBBBBBO....',
'....OBKBBKBO....',
'.....OBBBBO.....',
'....OBBBBBBO....',
'...OBBBBBBBBO...',
'...OBBBBBBBbO...',
'....OBBBBBbO....',
'.....OOOOOO.....',
]},
'옛 기념우표 앨범': { p: { O:'#241a10', W:'#f5f0e0', K:'#3a3226', R:'#c05050', L:'#5070c0' }, r: [
'.OOOOOOOOOOOOOO.',
'OWWWWWWWKWWWWWWO',
'OWRRWWWWKWWLLWWO',
'OWRRWWWWKWWLLWWO',
'OWWWWWWWKWWWWWWO',
'OWWLLWWWKWRRWWWO',
'OWWLLWWWKWRRWWWO',
'OWWWWWWWKWWWWWWO',
'.OOOOOOOOOOOOOO.',
]},
'60년대 싱글몰트 위스키': { p: { O:'#241a10', A:'#c87830', a:'#9a5a20', W:'#f5f0e0', b:'#5a3617', K:'#3a3226' }, r: [
'......OOO.......',
'......ObO.......',
'......OKO.......',
'......OAO.......',
'......OAO.......',
'.....OAAAO......',
'....OAAAAaO.....',
'....OAAAAaO.....',
'....OAWWWaO.....',
'....OAWWWaO.....',
'....OAAAAaO.....',
'....OAAAaaO.....',
'.....OOOOO......',
]},
'스위스 크로노그래프 시계': { p: { O:'#241a10', S:'#c9cdd4', s:'#8a8f9a', W:'#f5f0e0', K:'#3a3226' }, r: [
'.....OOOOO......',
'.....OKKKO......',
'.....OKKKO......',
'....OOOOOOO.....',
'...OSWWWWWSO....',
'...OSWWKWWSO....',
'...OSWWKKWSO....',
'...OSWWWWWSO....',
'....OOOOOOO.....',
'.....OKKKO......',
'.....OKKKO......',
'.....OOOOO......',
]},
'3캐럿급 다이아 목걸이': { p: { O:'#241a10', P:'#f0eaf2', s:'#b8bcc8', W:'#ffffff', l:'#9cc8f0' }, r: [
'..OO........OO..',
'.OssO......OssO.',
'.OssO......OssO.',
'..OsPO....OPsO..',
'...OPPO..OPPO...',
'....OPPOOPPO....',
'.....OPPPPO.....',
'......OPPO......',
'......OllO......',
'.....OlWWlO.....',
'......OllO......',
'.......OO.......',
]},
'고려 금동불상(전세품)': { p: { O:'#241a10', G:'#e8b23a', g:'#a3711d', K:'#3a3226', b:'#7a4418' }, r: [
'......OOOO......',
'.....OGGGGO.....',
'.....OGKKGO.....',
'.....OGGGGO.....',
'....OOGGGGOO....',
'...OGGGGGGGGO...',
'..OGgOGGGGOgGO..',
'..OGGGGGGGGGGO..',
'...OGGGGGGGGO...',
'..OGGGGGGGGGGO..',
'.OGGGGGGGGGGgGO.',
'.OOOOOOOOOOOOOO.',
'..ObbbbbbbbbbO..',
'...OOOOOOOOOO...',
]},
'40년대 진공관 라디오': { p: { O:'#241a10', B:'#8a5a2b', b:'#5a3617', W:'#f5f0e0', K:'#3a3226', G:'#e8b23a' }, r: [
'.OOOOOOOOOOOOOO.',
'OBBBBBBBBBBBBBBO',
'OBWWWWWBBKKKKKBO',
'OBWKWWWBBKbKbKBO',
'OBWWWWWBBKKKKKBO',
'OBWWWWWBBKbKbKBO',
'OBBBBBBBBKKKKKBO',
'OBBGBBBBBBBBGBBO',
'.OOOOOOOOOOOOOO.',
]},
'순금 두꺼비상 (한 냥)': { p: { O:'#241a10', G:'#e8b23a', g:'#a3711d', K:'#3a3226' }, r: [
'...OO......OO...',
'..OGGO....OGGO..',
'..OGKGOOOOGKGO..',
'...OGGGGGGGGO...',
'..OGGGGGGGGGGO..',
'.OGGGGGGGGGGgO..',
'.OGGOGGGGGGOgO..',
'.OGGGGGGGGGGgO..',
'..OGGGGGGGGgO...',
'..OOGGOOOOGGOO..',
'....OO....OO....',
]},
'조선 환도(추정)': { p: { O:'#241a10', S:'#d4d8de', s:'#9aa0aa', G:'#e8b23a', b:'#5a3617' }, r: [
'..............OO',
'.............OSO',
'............OSsO',
'...........OSsO.',
'..........OSsO..',
'.........OSsO...',
'........OSsO....',
'.......OSsO.....',
'......OSsO......',
'.....OGGO.......',
'....OGGO........',
'...ObbO.........',
'..ObbO..........',
'.OOO............',
]},
'중세 기사 투구': { p: { O:'#241a10', S:'#b8bec8', s:'#7a828e', K:'#26222a', R:'#c04040' }, r: [
'.......R........',
'......RR........',
'.....OOOOO......',
'....OSSSSSO.....',
'...OSSSSSSSO....',
'..OSSSSSSSSSO...',
'..OSOOOOOOOsO...',
'..OSKKKKKKKsO...',
'..OSOOOOOOOsO...',
'..OSSSSSSSSsO...',
'..OSsSSSSSssO...',
'...OsO...OsO....',
'....OO...OO.....',
]},
'명나라 청화백자': { p: { O:'#241a10', W:'#f2f4f0', w:'#d8dcd4', L:'#3a5aa8' }, r: [
'.....OOOO.......',
'....OWWWWO......',
'.....OWWO.......',
'....OWWWWO......',
'...OWWWWWWO.....',
'..OWWLLLWWWO....',
'..OWLWWWLWWO....',
'..OWLWLWLWWO....',
'..OWWLLLWWwO....',
'..OWWWWWWWwO....',
'...OWWWWWwO.....',
'....OOOOOO......',
]},
'조선 어보(왕실 인장)': { p: { O:'#241a10', G:'#e8b23a', g:'#a3711d', K:'#3a3226', R:'#b03030' }, r: [
'.....OOOO.......',
'....OGGGGOO.....',
'...OGKGGGGGO....',
'..OGGGGGGGGGO...',
'..OgOGGGGOgO....',
'...OGGGGGGO.....',
'..OGGGGGGGGGO...',
'.OGGGGGGGGGGgO..',
'.OGgggggggggGO..',
'.OGGGGGGGGGGgO..',
'.OOOOOOOOOOOOO..',
'..ORRRRRRRRRO...',
'...OOOOOOOOO....',
]},
'운석 조각': { p: { O:'#241a10', K:'#2c2830', k:'#45404a', l:'#7ce0e8' }, r: [
'....OOOOO.......',
'...OKkKKKO......',
'..OKKlKKKKO.....',
'.OKkKKKKlKKO....',
'.OKKKlKKKKKO....',
'.OKkKKKKKkKO....',
'..OKKKlKKKO.....',
'...OKKKKKO......',
'....OOOOO.......',
]},
// ── [Phase3] 신규 14종 ──
'자개 경대': { p: { O:'#241a10', B:'#5a3617', W:'#e8f0f4', s:'#9aa0aa', P:'#c8e8e0', p:'#e8c8e0' }, r: [
'...OOOOOOOOO....',
'..OBWWWWWWWBO...',
'..OBWWWsWWWBO...',
'..OBWWWWWWWBO...',
'...OOOOOOOOO....',
'.OBBBBBBBBBBBO..',
'.OBPpBPpBPpBBO..',
'.OBBBBBBBBBBBO..',
'.OBpBPpBPpBBBO..',
'.OOOOOOOOOOOOO..',
]},
'고가구 문갑': { p: { O:'#241a10', B:'#6a4020', b:'#4a2a12', G:'#c8a24a', K:'#2a1c0e' }, r: [
'.OOOOOOOOOOOOO..',
'.OBBBBBBBBBBBO..',
'.OBKBBGBBKBGBO..',
'.ObBBBBBBBbBBO..',
'.OBBGBBKBBGBBO..',
'.OBBBBBBBBBBBO..',
'.OOOOOOOOOOOOO..',
'..OKO.......OKO.',
'..OOO.......OOO.',
]},
'익선관(왕의 관모)': { p: { O:'#241a10', K:'#1c1a22', k:'#34303e', G:'#e8b23a' }, r: [
'..O..........O..',
'.OkO........OkO.',
'.OkkO......OkkO.',
'..OkkOOOOOOkkO..',
'...OKKKKKKKKO...',
'..OKKKKKKKKKKO..',
'..OKKKGGKKKKKO..',
'..OKKKKKKKKKKO..',
'...OKKKKKKKKO...',
'....OOOOOOOO....',
]},
'곤룡포 흉배': { p: { O:'#241a10', R:'#8a2030', r:'#6a1424', G:'#e8b23a', g:'#c8922a' }, r: [
'.OOOOOOOOOOOOO..',
'.ORRRRRRRRRRRO..',
'.ORGggGGgGGRrO..',
'.ORgRRGGRRgRrO..',
'.ORGgGGGGgGRrO..',
'.ORgRRGGRRgRrO..',
'.ORGGgGGgGGRrO..',
'.ORrrrrrrrrrrO..',
'.OOOOOOOOOOOOO..',
]},
'궁중 은장도': { p: { O:'#241a10', S:'#d4d8de', G:'#e8b23a', R:'#b03040', L:'#3a5aa8' }, r: [
'.OO.............',
'.OSO............',
'..OSO...........',
'...OSO..........',
'....OSO.........',
'.....OSO........',
'......OGO.......',
'.......OGRO.....',
'........OGLO....',
'.........OGRO...',
'..........OGO...',
'...........OO...',
]},
'청동 궁중 향로': { p: { O:'#241a10', T:'#3a6a5a', t:'#2a4a3e', G:'#5a8a6a', k:'#1c2a22' }, r: [
'.....OO..OO.....',
'....OTO..OTO....',
'....OOOOOOOO....',
'...OTTTTTTTTO...',
'..OTTGTTGTTGtO..',
'..OTTTTTTTTTtO..',
'..OtTTTTTTTttO..',
'...OTTTTTTTtO...',
'....OOOOOOOO....',
'....OkO..OkO....',
'...OOO....OOO...',
]},
'장군 갑주': { p: { O:'#241a10', K:'#3a3a44', k:'#26262e', R:'#7a2020', G:'#c8a24a', b:'#5a3617' }, r: [
'.....OOOOO......',
'....OKKKKKO.....',
'....OKGKGKO.....',
'..OOOOOOOOOOO...',
'.ORKKKKKKKKKRO..',
'.ORKkKkKkKkKRO..',
'.ORKKKKKKKKKRO..',
'.ORKkKkKkKkKRO..',
'..OKKKKKKKKKO...',
'..ObKkKkKkKbO...',
'...OOOOOOOOO....',
]},
'전통 각궁': { p: { O:'#241a10', B:'#8a5a2b', b:'#5a3617', W:'#e8e0d0', s:'#9aa0aa' }, r: [
'....OO..........',
'...OBBO.........',
'..OBBO.s........',
'.OBBO...s.......',
'.OBO.....s......',
'.ObO......s.....',
'.OBO.......s....',
'.OBBO.......s...',
'..OBBO.......s..',
'...OBBO......Ws.',
'....ObBO....OWO.',
'.....ObOOOOObO..',
'.......OOOO.....',
]},
'승자총통': { p: { O:'#241a10', T:'#4a4a3a', t:'#32322a', G:'#c8a24a', b:'#5a3617' }, r: [
'OOOO............',
'OTTOO...........',
'OTTTTOO.........',
'.OTtTTTOO.......',
'..OGTtTTTOO.....',
'...OTTtTTTTOO...',
'....OGTTtTTTTO..',
'.....OTTTtTTTO..',
'......ObbTTTO...',
'.......ObbOO....',
'........OOO.....',
]},
'군령기(장군 깃발)': { p: { O:'#241a10', R:'#a02030', r:'#7a1824', G:'#e8b23a', b:'#5a3617' }, r: [
'..OO............',
'..ObOOOOOOOOO...',
'..ObORRRRRRRRO..',
'..ObORGGGGRRRO..',
'..ObORGRRGRRrO..',
'..ObORGGGGRRrO..',
'..ObORRRRRrrrO..',
'..ObOOOOOOOOO...',
'..ObO...........',
'..ObO...........',
'..ObO...........',
'.OOOOO..........',
]},
'보석 세공 달걀': { p: { O:'#241a10', E:'#c8607a', e:'#a04860', G:'#e8b23a', W:'#f0f4f8', L:'#5a7ac8' }, r: [
'.....OOOOO......',
'....OEEEEEO.....',
'...OEWEEEEEO....',
'..OEEGEELEEEO...',
'..OEEEEEEEEeO...',
'..OELEEGEEEeO...',
'..OEEEEEEEeeO...',
'...OEEGEEEeO....',
'....OEEEEeO.....',
'.....OOOOO......',
'....OGGGGGO.....',
'.....OOOOO......',
]},
'금화 궤짝': { p: { O:'#241a10', B:'#6a4020', b:'#4a2a12', G:'#e8b23a', K:'#2a1c0e' }, r: [
'....GG..G.......',
'..OGGGGGGGO.....',
'.OOOOOOOOOOOOO..',
'.OBBBBBBBBBBBO..',
'.ObBBKKKBBBbBO..',
'.OBBBKGKBBBBBO..',
'.ObBBKKKBBBbBO..',
'.OBBBBBBBBBBBO..',
'.OOOOOOOOOOOOO..',
]},
'산호 왕관': { p: { O:'#241a10', C:'#d04848', c:'#a83232', G:'#e8b23a', W:'#f0e8e0' }, r: [
'..O....O....O...',
'.OCO..OCO..OCO..',
'.OCCO.OCO.OCCO..',
'..OCOOCCCOOCO...',
'..OCCCCCCCCCO...',
'..OcCWCCCWCcO...',
'..OGGGGGGGGGO...',
'..OGGGGGGGGGO...',
'...OOOOOOOOO....',
]},
'고서 초판본': { p: { O:'#241a10', W:'#e8dcc0', w:'#d0c4a0', K:'#3a3226', R:'#8a2030' }, r: [
'.OOOOOOOOOOOO...',
'.OWWWWWWWWWWOO..',
'.OWKWKKWKWWWORO.',
'.OWWWWWWWWWWORO.',
'.OWKKWKWKKWWORO.',
'.OWWWWWWWWWWORO.',
'.OWKWKKWWKWWORO.',
'.OWwWwWwWwWwORO.',
'.OOOOOOOOOOOOO..',
]},
};

// 픽셀아트 렌더러: 1px 격자를 box-shadow로 그린다. 데이터가 없으면 이모지 폴백.

function pixelArtHTML(item, sc) {
  const art = PIXEL_ART[item.name];
  if (!art) return `<span class="item-body">${item.emoji}</span>`;
  sc = sc || 6;
  const sh = [];
  art.r.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const col = art.p[row[x]];
      if (col) sh.push(`${(x + 1) * sc}px ${(y + 1) * sc}px 0 0 ${col}`);
    }
  });
  const w = Math.max(...art.r.map(r => r.length)), h = art.r.length;
  return `<div class="px-wrap"><div class="pxart" style="left:${-((w / 2 + 1) * sc)}px; top:${-((h / 2 + 1) * sc)}px; width:${sc}px; height:${sc}px; box-shadow:${sh.join(',')}"></div></div>`;
}

// 실물 검수: 아이템별 감정 포인트 3부위 (부위 점수 1~5로 상태를 보여준다)

Object.assign(globalThis, { PIXEL_ART, pixelArtHTML });
export { PIXEL_ART, pixelArtHTML };
